scrape_configs:
  - job_name: 'service'
    scrape_interval: 15s

    static_configs:
      - targets:
          - 'service:8081'

  - job_name: 'prometheus'
    scrape_interval: 15s

    static_configs:
      - targets:
          - 'prometheus:9090'